name: Compile and deploy LaTeX document

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Compile documents
    steps:
    - uses: actions/checkout@v2
    - name: Init
      run: |
        mkdir output
    
    - name: Compile Carentan
      uses: ftsrg/document-converter-actions@master
      with:
        makefile-arguments: -C Carentan/src

    - name: Compile Foy
      uses: ftsrg/document-converter-actions@master
      with:
        makefile-arguments: -C Foy/src
    
    - name: Compile Hill
      uses: ftsrg/document-converter-actions@master
      with:
        makefile-arguments: -C Hill400/src

    - name: Compile Hürtgen
      uses: ftsrg/document-converter-actions@master
      with:
        makefile-arguments: -C Hürtgen-forest/src

    - name: Compile Omaha
      uses: ftsrg/document-converter-actions@master
      with:
        makefile-arguments: -C Omaha-Beach/src
    
    - name: Compile Purple
      uses: ftsrg/document-converter-actions@master
      with:
        makefile-arguments: -C Purple-Heart-Lane/src

    - name: Compile Sainte-Marie-du-Mont
      uses: ftsrg/document-converter-actions@master
      with:
        makefile-arguments: -C Sainte-Marie-du-Mont/src

    - name: Compile Sainte-Mére-Église
      uses: ftsrg/document-converter-actions@master
      with:
        makefile-arguments: -C Sainte-Mére-Église/src
    
    - name: Compile Utah-Beach
      uses: ftsrg/document-converter-actions@master
      with:
        makefile-arguments: -C Utah-Beach/src

    - name: Compile Stalingrad
      uses: ftsrg/document-converter-actions@master
      with:
        makefile-arguments: -C Stalingrad/src

    - name: Cleanup
      run: |
        echo "https://github.com/$GITHUB_REPOSITORY/commit/$GITHUB_SHA" > output/README.md
        mv Carentan/pdf/*.pdf output/
        mv Foy/pdf/*.pdf output/
        mv Hill400/pdf/*.pdf output/
        mv Hürtgen-forest/pdf/*.pdf output/
        mv Omaha-Beach/pdf/*.pdf output/
        mv Sainte-Marie-du-Mont/pdf/*.pdf output/
        mv Purple-Heart-Lane/pdf/*.pdf output/
        mv Sainte-Mére-Église/pdf/*.pdf output/
        mv Utah-Beach/pdf/*.pdf output/
        mv Stalingrad/pdf/*.pdf output/

    - name: Deploy site and PDFs
      uses: maxheld83/ghpages@68f783a4f5313d776c1599e18479607e71c9c738  # v0.3.0
      env:
        BUILD_DIR: output/
        GH_PAT: x-access-token:${{ secrets.GITHUB_TOKEN }}
      # https://github.com/marketplace/actions/twitter-together#setup
      # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsif
      # https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'